rails/homepage

- doctrine.html
There are eight pillars, not seven.
> Fix numbering of pillars

- trademarks.html
> "Examples do", not "examples does"

- trademarks.html
> Quick grammar correction on trademarks

- doctrine.html
Fix typo involving the amount of meals.
> Eight meals, not seven

- doctrine.html
I've removed an unnecessary "you" that interrupted the flow of a sentence. It must've snuck in there somehow! (done in the spirit of "fixing a misspelling" as you laud at the end of the essay)
:)
> fix minor typo

- doctrine.html
> Small grammar changes

- index.html
Updated release announcement on index page.
> Update Latest release version on Homepage

- doctrine.html
Not 100% sure but "We should embrace this inasmuch as it" makes more sense to me than "We should embrace inasmuch it "
> Small grammar fix

- index.html
Updates homepage, links to the blog post announcing Rails 5.0.0.beta3
> Update to 5.0.0.beta3

- conduct.html
This was previously discussed internally. The new version cleared up a few confusion points.
/cc @dhh for final review
> Upgrade to Contributor Covenant v1.4

- index.html
Adds the rails 5 beta 4 blog post to the rails homepage
> Add rails 5 beta 4 announcement to the homepage

- index.html
Adding Rails 5.0.0.rc1 announcement to the homepage
> Add rails 5.0.0.rc1 announcement

- _config.yml
- _layouts/default.html
- _layouts/page.html
- community.html
- conduct.html
- doctrine.html
- everything-you-need.html
- index.html
- maintenance.html
- security.html
> Revert "Add baseurl for assets"

- index.html
> Fix wrong release date and url

- _config.yml
- _layouts/default.html
- _layouts/page.html
- community.html
- conduct.html
- doctrine.html
- everything-you-need.html
- index.html
- maintenance.html
- security.html
Add baseurl to config file
Add baseurl to asset link in head tag
Add baseurl to image asset paths
> Add baseurl for assets

- index.html
> Rails 5.0.1

- index.html
"More than 4,200 people" -> "More than 4,500 people"
(per http://contributors.rubyonrails.org/)
> Update Rails Contributors number on homepage.

- community.html
The best Rails router I have ever used! 5/5 would buy again.
But seriously, contributing to Rails was a wonderful learning opportunity for me. Working on a codebase with the breadth, depth and legacy of Rails was an eye-opening experience that taught me skills I couldn't have picked up elsewhere. It has also been a privilege to learn from a team of seasoned developers and other contributors from the community.
🤝🌈🤗🦄💯 would come again!
I will unwatch the repositories, so that I'm more likely to notice @mentions on issues that needs my attention (feel free to ping me still!). You can also find me on basecamp/twitter/IM if anything comes up. 😄
> What An Incredible Journey!

- index.html
This PR updates the link in the red box on the frontpage.
> Latest release is Rails 5.1.1

- index.html
> 5.1.2 released

- _layouts/doctrine.html
- doctrine.html
- doctrine/ru.html
- lib/language_switcher.js
- style.css
> Add language switcher

- index.html
updated to released version 5.1.5
> Update latest version link

- community.html
Hello!
I hope to add the new rails committer who is Yuji Yaginuma (@y-yagi) to community page.
> Add @y_yagi to the committer team on community page

- _config.yml
Added og:image same as [weblog](https://github.com/rails/weblog/blob/gh-pages/_config.yml#L19-L23) to configuration.
> Add og:image config

- index.html
Rails 5.2.0 has been released :tada:
> Update latest version to 5.2.0

- index.html
This PR updates the latest Rails version announcement link to 5.2.3.
> Update latest version to 5.2.3

- _config.yml
- _layouts/default.html
- index.html
> Updates accessibility for 100% on Lighthouse audit

- community.html
> Add myself to the committer team

- .github/workflows/lint.yml
- .markdownlint.yml
- README.md
Add a Markdownlint config file.
https://www.npmjs.com/package/markdownlint-cli
Lint the Markdown for rules:
MD009 Trailing spaces
MD034 Bare URL used
> Add a GitHub action to lint the Markdown.

- index.html
I guess it's worth to add it to the main navigation
> Add a link to Rails forum

- index.html
This PR updates the Rails version to 6.1.3.1
> Update latest version to 6.1.3.1

- .github/workflows/lint.yml
- README.md
> Update the Lint workflow to the latest versions

- _layouts/doctrine.html
- doctrine/fr.html
- Rails doctrine translated to French
---
- Languages menu
---
- Doctrine in French - Top
---
Many Thanks to you ! :stuck_out_tongue_winking_eye:
> I18n(French): add French doctrine
