rails/homepage

everything-you-need.html
This updates the capitalization of "Github" to be "GitHub" since that is how it is spelt on the homepage of the Rails site and on GitHub.
=> Fix capitalization of GitHub on "Everything You Need" page

doctrine.html
Was reading the document and noticed this.
=> Replaced markdown _ with <em> tags

doctrine.html
"a association" to "an association"
=> fix a small typo

style.css
The font-size on mobile displays means that only a small amount of text appears on the page, requiring a lot of scrolling to read it. I propose that the font-size is reduced to 18px, which changes it from this:
To the (still quite readable) this:
=> Reduce font size on mobile displays

index.html
This is a trivial change, but figured I'd PR it regardless:
"4,200 people already have their code in Rails" could be interpreted as those people having written _apps_ in Rails. This commit changes the language to be more clear that those 4,200 people have contributed code to Rails itself.
=> Clarify contribution language

community.html
No biggie :-)
I'm getting the [new site](https://rubyheroes-production-pr-2.herokuapp.com/) ready and I appreciate the link by the way.
=> Fix little typo on Ruby Hero Awards

maintenance.html, security.html
Copy over the new maintenance policy from the release post:
http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/
Summed up:
* Only 5.0.x gets bug fixes.
* Only 5.0.x and 4.2.x gets security fixes.
cc @rafaelfranca
=> Update maintenance policy to include Rails 5.

style.css
Consistent color on nav links
Add border bottom to hyperlinks (hover)
Add hover effect to red button
@fxn Hi Xavier! Here are the first couple of changes I suggested in the email. See changes live at https://vis-kid.github.io/homepage/. Happy to continue in this direction if you are happy with the results. 😃 
Nav link colors:
Before: Three colors
After: Two colors
Links with border-bottom on hover:
Button with hover:
Button without hover:
=> Tweak link styles and button

_config.yml, _layouts/default.html, _layouts/page.html, community.html, conduct.html, doctrine.html, everything-you-need.html, index.html, maintenance.html, security.html
Assets now stay intact on deployed gh-pages branch from fork
Add `baseurl: /homepage` to config file (user/org.github.io/homepage)
Add baseurl to style asset link in head tag
Add baseurl to image asset paths
=> Add baseurl for assets

security.html
The [security page](http://rubyonrails.org/security/) mentions "CRSF" - I think this is supposed to be "CSRF" instead.
=> Fix CSRF typo on the security page

doctrine.html
Previously the sentence (minus subordinate clauses) read "Yet it'd be hard that the power has doomed Ruby," which doesn't seem to be what's intended. Adding in "to argue that" seems to be the intent, so the core of the sentence is "Yet it'd be hard to argue that the power has doomed Ruby." I also added em-dashes to separate out a subordinate clause to make "it'd be hard to argue" easier to follow.
=> Add missing verb to doctrine page

index.html
This PR changes the text in the call-to-action on the frontpage.
=> Bump to v5.1.0.rc1 in the frontpage call-to-action

404.html
This isn't really a big deal, but it's a bit nicer?
=> Use a proper apostrophe on the 404 page.

index.html, security.html
I've changed weblog (GitHub page)'s protocol.
See: Custom domains on GitHub Pages gain support for HTTPS
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
=> Use https with weblog URI

trademarks.html
It seems like GoldieBlox has moved their store to be on Amazon.com.
=> Replace dead link on Ruby Rails doll

index.html
This PR updates the latest Rails version announcement link to 6.0.0.
https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/
=> Update latest version to 6.0.0

security.html
The latter contains more details about the versioning, as well as information about the Severe Security Issues category. Kudos to @dawnpm for pointing this out. Moreover, this deduplicates versioning information between the two pages.
Note the deployed Maintenance Policy page is still a major version behind. I couldn't find an open issue around that... Anyway, those versions were updated in https://github.com/rails/rails/commit/1c3c4f053f5b00dce5ed53570b2938977b830289.
Let us know what you think!
=> link from the Security Policy to the Maintenance Policy

index.html
This PR updates the latest Rails version announcement link to 6.0.2.
https://weblog.rubyonrails.org/2019/12/13/Rails-6-0-2-has-been-released/
=> Update latest version to 6.0.2

index.html
This PR updates the latest Rails version announcement link to 6.0.2.2.
https://weblog.rubyonrails.org/2020/3/19/Rails-6-0-2-2-and-5-2-4-2-has-been-released/
=> Update latest version to 6.0.2.2

index.html
This PR updates the latest Rails version announcement link to 6.0.3.
https://weblog.rubyonrails.org/2020/5/6/Rails-6-0-3-has-been-released/
=> Update latest version to 6.0.3

index.html
This PR updates the latest Rails version announcement link to 6.0.3.1.
https://weblog.rubyonrails.org/2020/5/18/Rails-5-2-4-3-and-6-0-3-1-have-been-released/
=> Update latest version to 6.0.3.1

index.html
Just noticed the home page hadn't been updated yet.
https://weblog.rubyonrails.org/2020/6/17/Rails-6-0-3-2-has-been-released/
=> Updating latest release version on home page.

index.html
@kaspth I just checked the home page and realized there was two instances of the date, but since I only saw one on the site, I wasn't looking for two. This fixes the second one.
=> Fixing instances of latest version release date.

index.html
This PR updates the latest Rails version announcement link to 6.0.3.3.
https://weblog.rubyonrails.org/2020/9/10/Rails-5-2-4-4-and-6-0-3-3-have-been-released/
=> Update latest version to 6.0.3.3

index.html
This PR updates the latest Rails version announcement link to 6.0.3.4.
https://weblog.rubyonrails.org/2020/10/7/Rails-6-0-3-4-has-been-released/
=> Update latest version to 6.0.3.4

index.html
This PR updates the latest Rails version announcement link to 6.1.2.1.
https://weblog.rubyonrails.org/2021/2/10/Rails-5-2-4-5-6-0-3-5-and-6-1-2-1-have-been-released/
=> Update latest version to 6.1.2.1

index.html
This PR updates the latest Rails version announcement link to 6.1.3.
https://weblog.rubyonrails.org/2021/2/17/Rails-6-1-3-has-been-released/
=> Update latest version to 6.1.3

index.html
This PR updates the latest Rails version announcement link to 6.1.3.2.
https://weblog.rubyonrails.org/2021/5/5/Rails-versions-6-1-3-2-6-0-3-7-5-2-4-6-and-5-2-6-have-been-released/
=> Update latest version to 6.1.3.2

community.html
Freenode is going through some changes - remove the reference until we know what's next.
Some people are gathering in #rubyonrails on Libera.chat, but it's still early on that front.
=> Remove Freenode reference in community page

doctrine.html
noun 'subtlety' incorrectly used in place of adverb 'subtly'
=> Typo in doctrine.html

index.html
This PR updates the latest Rails version announcement link to 6.1.4.1.
https://weblog.rubyonrails.org/2021/8/19/Rails-6-0-4-1-and-6-1-4-1-have-been-released/
=> Update latest version to 6.1.4.1
